apiVersion: v1
kind: Namespace
metadata:
  name: hello-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
  namespace: default
  annotations:
        prometheus.io/scrape: 'true'
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
            failureThreshold: 2
          resources:
            requests:
              memory: "32Mi"
              cpu: "1m"
            limits:
              memory: "256Mi"
              cpu: "100m"  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-k8s
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:341707006720:certificate/7dd7319f-7cb9-4965-93c7-3d9c7b1d00a2
    alb.ingress.kubernetes.io/subnets: subnet-0d58ee1687f7eb911,subnet-0f3ff4b4c68f5e66f,subnet-0c2e8656722eda93e
spec:
  rules:
    - host: urbandev.sourcefuse.com
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-k8s
              servicePort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-k8s
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-k8s
  minReplicas: 2
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 200Mi
